#!/usr/bin/env python
# 
# Jonathan Foote
# jmfoote@loyola.edu
#
# **** WARNING (2014-01-06) **** 
# This code is untested
# This idea may be crackheaded; this is just a toy
# ********
# 
# A quick hack to play with the idea of figuring out who is
# (somewhat) responsible for bugs in a codebase. Like so:
# 1. Find commits with bug fix strings in them
# 2. Figure out what files/lines the bug fix modified
# 3. Determine who was the last person to modify those lines before the bug fix

import subprocess, re, sys, os, json, difflib

# see http://wiki.python.org/moin/PrintFails
import codecs, locale
sys.stdout = codecs.getwriter(locale.getpreferredencoding())(sys.stdout) 

def get_edits(commit):
    '''
    Gets {filepath: [lines]} removed in commit
    '''
    edits = {}

    # get filepath, line_numbers that were removed with the bug fix
    # via: diff bugfix commit with parent and use external diff hack to extract line numbers

    # TODO: the python-based external diff hack below may break if a binary was modified 
    env = os.environ
    env["GIT_EXTERNAL_DIFF"] = "python -c 'import sys, json; print json.dumps([sys.argv[1], open(sys.argv[2]).read(), open(sys.argv[5]).read()])'"
    cmd = ["git", "diff", commit + "^!"]
    try:
        # prints GIT_EXTERNAL_DIFF args as a json string
        # path old-file old-hex old-mode new-file new-hex new-mode
        out = subprocess.check_output(cmd, env=env)
    except subprocess.CalledProcessError as e:
        # diff returns non-zero regularly
        out = e.output
    for line in out.splitlines():
        obj = json.loads(line) 

        # custom diff to get modified line numbers
        path, old_file, new_file = obj
        i = 1 # line counting starts at 1!
        lines = []
        for diff_out in difflib.ndiff(old_file.splitlines(), new_file.splitlines()):
            if (diff_out[:2] == "+ " or # new line in new file
                diff_out[:2] == "? "):  # helper line
                # don't advance position in old file
                continue
            elif diff_out[:2] == "- ": # modified line in old file
                lines.append(i)
            i += 1

        # store results 
        if lines:
            edits[path] = edits.get(path, []) + lines

    return edits

ins_regex = re.compile("^.* ([\d]+) insertions.*$")
del_regex = re.compile("^.* ([\d]+) deletions.*$")
def get_change_count(author):
    # 3 files changed, 14 insertions(+), 7 deletions(-)
    lines = subprocess.check_output(["git", "log", '--author=%s' % author, "--oneline", "--shortstat"]).splitlines()
    changes = 0
    for line in lines:
        m = re.match(ins_regex, line)
        if m:
            changes += int(m.groups()[0])
        #m = re.match(del_regex, line)
        #if m:
        #    changes += int(m.groups()[0])
    return changes

blame_cache = {}
author_regex = re.compile("^.*\(([^\)]*)[\d]{4}-[\d]{2}-[\d]{2}.*$")
# ^^ first string to the left of a date in parens ? :\
def get_editor(commit, filepath, line_num):
    '''
    Returns last editor of line at filepath in commit
    '''

    if (commit, filepath) in blame_cache.keys():
        lines = blame_cache[(commit, filepath)]
    else:
        lines = subprocess.check_output(["git", "blame", "-M", 
            # slow/better? "-C", "-C", filepath, commit]).splitlines()
            filepath, commit]).splitlines()
        blame_cache[(commit, filepath)] = lines
    author = re.match(author_regex, lines[line_num-1]).groups()[0].strip()
    author = author.decode("utf-8")
    return author

if __name__ == "__main__":
    try:
        commits = subprocess.check_output(["git", "log", "--all", "-M", "-C", 
            "--format=%H"] + sys.argv[1:]).splitlines()
    except subprocess.CalledProcessError as e:
        sys.stderr.write(e.output)
        sys.exit(e.returncode)
    
    partial_regex = re.compile("^.*Partial-Bug: #([\d]+).*$")
    related_regex = re.compile("^.*Related-Bug: #([\d]+).*$")
    close_regex = re.compile("^.*Closes-Bug: #([\d]+).*$")
    # ^^ recommended Gerritt bug-fix strings
    # TODO: handle Partial/Related with per-bug immunity
    
    bugs = {}
    i = 0
    # 1. Find a commit that has a bug fix
    for commit in commits:
        body = subprocess.check_output(["git", "log", "-M", "-C", "-1", "-U", 
            "--name-only", "--format=%B", commit]).replace("\n", " ").decode("utf-8")
        m = re.match(close_regex, body)
        if m: # commit closes a bug
            bug_id = int(m.groups()[0])
            # 2. Get files + lines that were removed in this fix
            edits = get_edits(commit)
    
            # 3. Get names of people who edited those lines
            for filepath, mlines in edits.iteritems():
                if not os.path.exists(filepath) or os.path.isdir(filepath):
                    # file was deleted in commit?
                    continue
                for mline in mlines:
                    editor = get_editor(commit+"^", filepath, mline)
                    bugs[editor] = bugs.get(editor, []) + [(bug_id, commit, filepath, mline)]
                    '''
                    # this describes each blame
                    print "*" * 12
                    print u"bug %s fixed in %s: introduced by %s at %s:%s" % \
                            (bug_id, commit, editor, filepath, mline)
                    print u"\t", body
                    '''
        i += 1
        if i % 100 == 0:
            print "%d/%d commits processed..." % (i, len(commits))

    # Compute stats for each editor
    stats = {}
    for editor, bug_data in bugs.items():
        added = get_change_count(editor)
        ratio = float(len(bug_data)) / added
        stats[editor] = {'added':added, 'ratio': ratio}

    # Print results
    fmt = u'{0:20} {1:>20} {2:>20} {3:>20}'
    print fmt.format("name", "bug-lines-removed", "total-lines-added", "ratio")
    for editor, bug_data in sorted(bugs.items(), key=lambda i:stats[i[0]]['ratio']):
        print fmt.format(editor, len(bug_data), stats[editor]['added'], stats[editor]['ratio'])
